services:
  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:v1.8.2
    command: --path.rootfs=/host
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - "/:/host:ro,rslave"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.1.0
    restart: unless-stopped
    user: root
    environment:
      GOMAXPROCS: 1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /data/prometheus:/prometheus:rw
    extra_hosts:
      - host.docker.internal=host-gateway
  victoria-metrics:
    container_name: victoria-metrics
    image: victoriametrics/victoria-metrics:v1.110.0
    command: -promscrape.config=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    environment:
      GOMAXPROCS: 1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /data/victoria-metrics:/victoria-metrics-data:rw
    extra_hosts:
      - host.docker.internal=host-gateway
    deploy:
      resources:
        limits:
          cpus: 1
  grafana:
    container_name: grafana
    image: grafana/grafana:11.5.0
    restart: unless-stopped
    user: root
    environment:
      GF_PLUGINS_PREINSTALL: victoriametrics-metrics-datasource
      GF_SERVER_ROOT_URL: https://grafana.lapwingcloud.com/
    volumes:
      - /data/grafana:/var/lib/grafana:rw
  nginx:
    container_name: nginx
    image: library/nginx:1.26.2
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/grafana.conf:/etc/nginx/conf.d/grafana.conf:ro
